s_sim_name_suffix: "plotting_only_BIG_RUN_local_mode_1_epoch_2_years_no_oversampling_xentropy"

# Debug configuration overrides for local machine debugging.
s_force_data_preprocessing: false  # This forces data preprocessing instead of attempting to load preprocessed data

# If active loads sim s_plot_sim_name and runs plotting pipeline
s_plotting_only: true  # Ensure plotting is enabled for debug runs

# s_plot_sim_name: Simulation name for plotting
s_plot_sim_name: "Run_20250430-174941BIG_RUN_local_mode_1_epoch_2_years_no_oversampling_xentropy"

# Save data loader variables
s_data_loader_vars_path: "/home/jan/nowcasting_project/weather_data/data_loader_vars"

s_save_dir: '/home/jan/nowcasting_project/results'
s_prediction_dir: '/home/jan/nowcasting_project/weather_data/predictions/'

# Max number of frames in processed data set for debugging (validation + training)
# [Disabled when set to None]
s_max_num_filter_hits: null  # 4 or None

s_max_epochs: 1  # Max number of epochs, affects scheduler

# In case only a specific time period of data should be used, otherwise set to None.
# Influences RAM usage.
s_crop_data_time_span:
  - "2019-01-01T00:00"
  - "2020-12-01T00:00"

# Time span that bin frequencies are calculated for
s_time_span_for_bin_frequencies:
  - "2019-01-01T08:00"
  - "2019-01-01T08:05"

# The time duration of the chunks, goes into dataset.resample
s_split_chunk_duration: "1D"

# TIME RATIO, DOES NOT DIRECTLY CORRESPOND THE SAMPLE RATIO DUE TO FILTERING.
s_ratio_train_val_test: [0.7, 0.15, 0.15]

# Number of steps per epoch in random sampler
s_train_samples_per_epoch: 4
s_val_samples_per_epoch: 4

# Data paths and variables
s_folder_path: "/home/jan/nowcasting_project/weather_data/radolan"
s_data_file_name: 'RV_recalc_rechunked.zarr'#' #"RV_recalc_rechunked.zarr"
s_data_variable_name: "RV_recalc"

s_dem_path: "/home/jan/nowcasting_project/weather_data/static/tiny_dem_from_old_desktop/dem_benchmark_dataset_1200_1100.zarr"

# Baseline paths and settings
s_baseline_path: "/mnt/4tb/mustein_server_data_backup/baselines/datasets/extrapolation_2019_2020.zarr"
s_baseline_variable_name: "extrapolation"
s_num_input_frames_baseline: 4

# Evaluation stuff
# s_subsample_dataset_to_len: 10000

# Hardware settings
s_num_workers_data_loader: 6
s_num_gpus: 1

# Model parameters
s_batch_size: 64 #110
s_upscale_c_to: 32  # 8

# DLBD settings
s_multiple_sigmas: [2, 16]

# Testing settings
s_testing: true  # Runs tests at the beginning
s_data_loader_chunk_size: 1